clc; clear all; close all;

%% Galata Brushless DC Motor Approximate Parameters
N = 14;                    % Number of poles in Rotor
N_s = 12;                  % Number of slots in Stator
Vphase = 22.2;             % Voltage of each phase (6S LiPo)
f = 50;                    % Frequency of each phase
omega = 2*pi*f;            % Angular frequency of each phase
N_winding = 8;            % Number of windings in each tooth
d = 0.001;                 % Diameter of copper wire
D_stator = 0.03168;        % Outer diameter of stator
L = 0.017;                 % Stack length
rho_cu = 1.72e-8;          % Resistivity of copper wire
Br = 1.2;                  % Magnet remanence for N52H
w = 0.002;                 % Thickness of tooth
mu0 = 4*pi*1e-7;           % Permeabilty of air
muR = 3000;                % Relative permeability of D19 24G
g = 0.0002;                % Air gap
L_tooth = 0.0072;          % Tooth length
L_yoke = 0.0012;           % Yoke Length
w_yoke = 0.00629;          % Yoke width
t_magnet = 0.0008;         % Magnet Thickness

%  Wire Length
L_wire = 2. * N_winding * N_s * (w + L + 2. * d);
% Phase resistance (ohm)
R_phase = 4. * rho_cu * L_wire /(pi*d^2);         
% Tooth reluctance
R_tooth = L_tooth/(muR * mu0 * w * L);
% Yoke reluctance 
R_yoke = L_yoke/(muR * mu0 * w_yoke * L);
% Airgap reluctance 
R_airgap = g/( mu0 * w_yoke * L);
% Total reluctance
R_total = R_tooth + R_yoke + R_airgap;
% Impedance of each Tooth
Z_tooth = R_phase + j * N_winding^2/R_total;
% Total impednace in each phase
Z_total = 4. * Z_tooth;
% Impedance of Y equivalent
Z_Y = Z_total/3.;
% Magnitude of Impedance
Z_abs = abs(Z_Y);
% Phase angle of impedance
Z_phase = angle(Z_Y);        % radians

% Angular speed range of rotor
omega_r = linspace(0,630,100);
% Airgap flux density
M = Br/(1 + g/t_magnet);
% Induced voltage in each phase
e_ind = (8 * M * N_winding * w_yoke * L * N * omega_r)/(2. * pi);
% Current amplitude in each phase
I_phase = (sqrt(2) * Vphase)/(3.* Z_abs);
% Induced Current
I_ind= e_ind/(4*R_phase);
% Total current
I_total = I_phase - I_ind * sqrt(2);
% Magnetic flux generated by Stator
B_phase = (I_phase * N_winding) / (R_total * w_yoke * L);
% Induced Magnetic Field in Stator Phases
B_ind = (I_ind * N_winding) / (R_total * w_yoke * L);

figure;
plot( 60 * omega_r /(2. * pi), e_ind)
pbaspect([3 1 1])
xlabel('RPM');
ylabel('e_{ind} (A)');
title('Induced EMF in each phase for varying RPM');
grid on;

figure;
plot( 60 * omega_r /(2. * pi), I_total)
pbaspect([3 1 1])
xlabel('RPM');
ylabel('I_{phase} (A)');
title('Current in each phase for varying RPM');
grid on;

% Here we generate harmonic functions
alpha_s = 2*pi/N_s;
beta = pi/(2*N); 

% Here we generate harmonic functions and their derivatives with respect to
% beta
[Fs, Fc, Fc_beta, Fs_beta, Feq_beta, phi_beta] = spatial_Fs_Fc(alpha_s, beta, N);

beta_vals = linspace(0, 2*pi, 200);

% Here we evaluate the harmonics functions with respect to beta values
Fc_vals = Fc(alpha_s, beta_vals, N);
Fs_vals = Fs(alpha_s, beta_vals, N);

% Here we plot values for varying beta values
figure;
plot(beta_vals, Fc_vals)
hold on
plot(beta_vals, Fs_vals)
xlabel('\beta');
ylabel('Harmonic Function Amplitudes');
title('Harmonic Function  Values of Interaction Energy');
legend('F_c', 'F_s');
grid on;

% Here we evaluate the derivatives of harmonics functions with respect to
% beta values
Fc_beta_vals = Fc_beta(alpha_s, beta_vals, N);
Fs_beta_vals = Fs_beta(alpha_s, beta_vals, N);
Feq_beta_vals = Feq_beta(alpha_s, beta_vals, N);
phi_beta_vals = phi_beta(alpha_s, beta_vals, N);

% Here we calculate the exact value of Fc_beta and Fs_beta
Fc_beta_exact = Fc_beta(alpha_s, beta, N);
Fs_beta_exact = Fs_beta(alpha_s, beta, N);
Feq_beta_exact = Feq_beta(alpha_s, beta, N);
phi_beta_exact = phi_beta(alpha_s, beta, N);

% Here we plot values for varying beta values
figure;
plot(beta_vals, Fc_beta_vals)
hold on
plot(beta_vals, Fs_beta_vals)
hold on
plot(beta_vals, Feq_beta_vals)
hold on
plot(beta, Fc_beta_exact, '*')
hold on
plot(beta, Fs_beta_exact, '*')
hold on
plot(beta, Feq_beta_exact, '*')
xlabel('\beta');
ylabel('Harmonic Function Amplitudes');
title('Derivatives of Harmonic Functions with respect to \beta');
legend('F_c', 'F_s','F_{eq}' ...
,'F_c(\beta_{exact})','F_s(\beta_{exact})','F_{eq}(\beta_{exact})','Interpreter','latex');
grid on;

% Here we calculate the averages of the harmonic functions derivatives
Feq_beta_ave = sum(Feq_beta(alpha_s, linspace(0,2*pi/N, 10), N))/10;
phi_beta_ave = sum(phi_beta(alpha_s, linspace(0,2*pi/N, 10), N))/10;

figure;
plot(beta_vals, phi_beta_vals)
hold on
plot(beta, phi_beta_exact, '*')
xlabel('\beta');
ylabel('\phi');
title('Phase Shift');
legend('\phi','\phi(\beta_{exact})','Interpreter','latex');
grid on;

% Torque Generated by the interaction of Magnet Magnetic Field
Torque = 2 * Feq_beta_ave * (M * B_phase * L * g * D_stator)/mu0 - 6 * Feq_beta_ave * (M * B_ind * L * g * D_stator)/mu0;
Power = Torque .* omega_r;
Power_elec = I_total.^2 * R_phase;
Efficiency = Power./Power_elec;
figure;
plot( 60 * omega_r /(2. * pi), Torque)
pbaspect([3 1 1])
xlabel('RPM');
ylabel('Torque (Nm)');
title('Torque for varying RPM');
grid on;

figure;
plot( 60 * omega_r /(2. * pi), Power)
%hold on
%plot( 60 * omega_r /(2. * pi), Power_elec)
pbaspect([3 1 1])
xlabel('RPM');
ylabel('Power (W)');
%legend('Mechanical','Electrical')
title('Power for varying RPM');
grid on;

figure;
plot( 60 * omega_r /(2. * pi), Efficiency)
pbaspect([2 1 1])
xlabel('RPM');
ylabel('Efficiency');
title('Efficency for varying RPM');
grid on;

